//! `cfs::docs` — the **anti-drift documentation generator** (ticket t40).
//!
//! `cargo xtask gen-docs` calls [`gen_docs`] (write mode) or [`check_docs`] (CI `--check`
//! mode). Both render the three generated reference docs **from the binary's own data** so the
//! published reference can never drift from the code:
//!
//! - `docs/language.md` ← [`cfs_lang::RESERVED_KEYWORDS`] + [`cfs_lang::grammar_ebnf`] (the
//!   frozen §3 vocabulary + the grammar; the reserved-word table is the one frozen slice).
//! - `docs/drivers.md` ← [`crate::catalog::driver_catalog`] (archetypes / capabilities /
//!   procedures / codecs, folded from the t39 describe surface — never hand-authored).
//! - `docs/server.md` ← the frozen server-DDL keyword set (CREATE ENDPOINT|TRIGGER|JOB|VIEW|
//!   WEBHOOK|POLICY) + the t36 deployment mapping prose.
//!
//! The render functions are **pure** `-> String`: no creds, no live tokens, only schema +
//! capabilities (RFD §10). The golden/idempotency test ([`tests`]) and the `--check` mode
//! compare the rendered string to the committed file; a keyword/driver/codec change that is not
//! reflected in `docs/` fails the check (anti-drift enforcement, RFD §3).

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use cfs_core::{grammar_ebnf, Capabilities, RESERVED_KEYWORDS};

use crate::catalog::{driver_catalog, Catalog, DriverDoc};

/// The three generated reference files, relative to the repo root.
pub const LANGUAGE_DOC: &str = "docs/language.md";
/// The generated driver-catalog doc.
pub const DRIVERS_DOC: &str = "docs/drivers.md";
/// The generated server-guide doc.
pub const SERVER_DOC: &str = "docs/server.md";

/// A do-not-edit banner stamped at the top of every generated doc, pointing the editor at the
/// generator (so a human never hand-edits a generated file and reintroduces drift).
fn generated_banner(source: &str) -> String {
    format!(
        "<!-- GENERATED by `cargo xtask gen-docs` from {source}. DO NOT EDIT BY HAND. -->\n\
         <!-- Re-run `cargo xtask gen-docs` after changing the source; CI fails on drift. -->\n\n"
    )
}

/// Render `docs/language.md` from the frozen reserved-word set + the EBNF grammar.
#[must_use]
pub fn render_language() -> String {
    let mut s = generated_banner("cfs-lang (RESERVED_KEYWORDS + grammar_ebnf)");
    let _ = writeln!(s, "# cfs language reference\n");
    let _ = writeln!(
        s,
        "cfs is **one small pipe-SQL grammar** — a *closed core* plus three open registries \
         (paths, functions/procedures, codecs). A new backend adds **zero** keywords: a new \
         service is a new mount, a new action a registered procedure, a new format a registered \
         codec (RFD-0001 §3). This page is generated from the binary's own frozen vocabulary, so \
         it cannot drift from the lexer.\n"
    );

    let _ = writeln!(s, "## Reserved keywords (frozen — RFD §3)\n");
    let _ = writeln!(
        s,
        "The keyword set is **frozen**: it has exactly {} entries and changing it requires \
         editing the one committed source slice (`crates/lang/src/keywords.rs`) and regenerating \
         this doc. Adding a keyword without updating this table fails CI by design.\n",
        RESERVED_KEYWORDS.len()
    );
    let _ = writeln!(s, "| # | keyword |");
    let _ = writeln!(s, "|---|---------|");
    for (i, kw) in RESERVED_KEYWORDS.iter().enumerate() {
        let _ = writeln!(s, "| {} | `{}` |", i + 1, kw);
    }
    s.push('\n');

    let _ = writeln!(s, "## Grammar (EBNF)\n");
    let _ = writeln!(
        s,
        "The pipe-SQL grammar. Every UPPERCASE terminal is a frozen reserved keyword above.\n"
    );
    let _ = writeln!(s, "```ebnf\n{}```\n", grammar_ebnf());

    let _ = writeln!(s, "## Purity invariant (RFD §3/§6)\n");
    let _ = writeln!(
        s,
        "Every cfs function and prelude alias is **pure**: it produces a `Plan` (an effect-plan \
         node), it performs no I/O. `SEND(d)` does not send mail — it desugars to a \
         `CALL mail.send` node in a `Plan`. Nothing happens until `COMMIT` applies the plan; \
         `PREVIEW` (the default) shows the plan without touching the World. This is what makes \
         the agent loop safe: **DESCRIBE → write a statement → PREVIEW → COMMIT**.\n"
    );

    let _ = writeln!(s, "## Open-registry governance (RFD §3)\n");
    let _ = writeln!(
        s,
        "The closed core (the frozen keywords + operators above) is the *only* part of cfs that \
         is not extensible. Everything a new backend needs is a registry entry:\n\n\
         - **paths** — a new mount (e.g. `/mail`, `/s3`); see [drivers.md](drivers.md).\n\
         - **functions / procedures** — a registered `CALL driver.action(..)` + pure prelude \
           aliases.\n\
         - **codecs** — a registered `DECODE`/`ENCODE` format; see [drivers.md](drivers.md).\n\n\
         Because the core is frozen, the AI learns the grammar **once** and every backend speaks \
         it.\n"
    );

    s
}

/// Render one driver's catalog row, capabilities shown explicitly (supported AND unsupported).
fn render_driver(s: &mut String, d: &DriverDoc) {
    let _ = writeln!(s, "### `{}` — {:?}\n", d.mount, d.archetype);
    let _ = writeln!(s, "- example node: `{}`", d.example_path);
    let _ = writeln!(s, "- native verbs: {}\n", d.native_verbs);

    let _ = writeln!(
        s,
        "Universal verbs (✓ supported / ✗ rejected at parse time):\n"
    );
    let _ = writeln!(s, "| verb | supported |");
    let _ = writeln!(s, "|------|-----------|");
    for (verb, on) in capability_rows(&d.capabilities) {
        let _ = writeln!(s, "| `{verb}` | {} |", if on { "✓" } else { "✗" });
    }
    s.push('\n');

    if d.procedures.is_empty() {
        let _ = writeln!(s, "Procedures: _none_\n");
    } else {
        let _ = writeln!(
            s,
            "Procedures (`CALL {}.action(..)`):\n",
            mount_id(&d.mount)
        );
        let _ = writeln!(s, "| procedure | params | irreversible |");
        let _ = writeln!(s, "|-----------|--------|--------------|");
        for p in &d.procedures {
            let params = p
                .params
                .iter()
                .map(|pm| format!("{}: {:?}", pm.name, pm.ty))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(
                s,
                "| `{}` | {} | {} |",
                p.name,
                if params.is_empty() {
                    "—".into()
                } else {
                    params
                },
                if p.irreversible { "yes" } else { "no" }
            );
        }
        s.push('\n');
    }

    if d.aliases.is_empty() {
        let _ = writeln!(s, "Prelude aliases: _none_\n");
    } else {
        let aliases = d
            .aliases
            .iter()
            .map(|(n, t)| format!("`{n}` → `{t}`"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(s, "Prelude aliases: {aliases}\n");
    }

    let pd = &d.pushdown;
    let _ = writeln!(
        s,
        "Pushdown: where={} project={} limit={} order={} join={} aggregate={} distinct={} group_by={}\n",
        pd.where_, pd.project, pd.limit, pd.order, pd.join, pd.aggregate, pd.distinct, pd.group_by
    );
}

/// Render `docs/drivers.md` from the live driver catalog.
#[must_use]
pub fn render_drivers() -> String {
    let cat: Catalog = driver_catalog();
    let mut s = generated_banner("the live driver catalog (cfs::catalog::driver_catalog)");
    let _ = writeln!(s, "# cfs driver catalog\n");
    let _ = writeln!(
        s,
        "Each backend is a **mount** in the paths registry (RFD §3). Every node maps onto one of \
         four archetypes (Blob / Relational / Append / ObjectGraph) and declares which universal \
         verbs it supports — **unsupported verbs are rejected at parse time** (RFD §5), so the AI \
         never plans a rejected op. This catalog is generated from the binary's describe surface; \
         it cannot drift from the drivers.\n"
    );

    let _ = writeln!(s, "## Drivers\n");
    for d in &cat.drivers {
        render_driver(&mut s, d);
    }

    let _ = writeln!(
        s,
        "## Codecs (the shared `DECODE`/`ENCODE` registry, RFD §4)\n"
    );
    let _ = writeln!(
        s,
        "Codecs bridge blob ↔ relational independent of driver identity. Builtin formats:\n"
    );
    for c in &cat.codecs {
        let _ = writeln!(s, "- `{c}`");
    }
    s.push('\n');
    s
}

/// Render `docs/server.md` from the frozen server-DDL keyword set + the t36 deployment mapping.
#[must_use]
pub fn render_server() -> String {
    let mut s = generated_banner("the frozen server-DDL keyword set + the t36 deployment mapping");
    let _ = writeln!(s, "# cfs server guide\n");
    let _ = writeln!(
        s,
        "`cfs serve <config.cfs>` boots the server (RFD §8). A server config is a set of frozen \
         `CREATE …` bindings — sugar over the same write surface the CLI uses. The DDL keywords \
         are part of the closed core (see [language.md](language.md)); a new binding form cannot \
         be invented.\n"
    );

    let _ = writeln!(s, "## Bindings (`CREATE …`, RFD §8)\n");
    let _ = writeln!(s, "| binding | shape | what causes the plan to run |");
    let _ = writeln!(s, "|---------|-------|-----------------------------|");
    let _ = writeln!(
        s,
        "| `CREATE ENDPOINT` | `ENDPOINT <name> DO <stmt>` | an HTTP `fetch` to the endpoint route |"
    );
    let _ = writeln!(
        s,
        "| `CREATE TRIGGER` | `TRIGGER <name> ON <event> DO <stmt>` | an event/watcher firing |"
    );
    let _ = writeln!(
        s,
        "| `CREATE JOB` | `JOB <name> EVERY <interval> DO <stmt>` | the cron scheduler / Cron trigger |"
    );
    let _ = writeln!(
        s,
        "| `CREATE VIEW` | `[MATERIALIZED] VIEW <name> AS <pipeline>` | a query against the view |"
    );
    let _ = writeln!(
        s,
        "| `CREATE WEBHOOK` | `WEBHOOK <name> DO <stmt>` | a signed inbound `/hooks/...` POST |"
    );
    let _ = writeln!(
        s,
        "| `CREATE POLICY` | `POLICY <name> <predicate>` | (gate) blocks plans that violate it |"
    );
    s.push('\n');

    let _ = writeln!(s, "## Policy & least privilege (RFD §10)\n");
    let _ = writeln!(
        s,
        "`CREATE POLICY` gates writes by verb / path / irreversibility — an irreversible effect \
         (`REMOVE`, `CALL mail.send`) can be blocked or required to be explicitly acknowledged. \
         **Credentials are never inline in a config**: a binding references a stored account by \
         handle (`cfs account add <driver> <name>`), and no token is ever written to a config, a \
         log, or a generated doc. Examples below use placeholder handles only.\n"
    );
    let _ = writeln!(
        s,
        "```cfs\n\
         CREATE POLICY no_send POLICY deny CALL mail.send\n\
         CREATE ENDPOINT daily DO FROM /mail/inbox |> SELECT subject |> LIMIT 10\n\
         CREATE JOB digest EVERY 1h DO FROM /mail/inbox |> SELECT subject |> COMMIT\n\
         ```\n"
    );

    let _ = writeln!(s, "## Deployment mapping (t36, RFD §8)\n");
    let _ = writeln!(
        s,
        "The same bindings deploy onto two production hosts behind the `RuntimeHost` seam \
         (ADR-0005). `cfs` *documents* the mapping here; ticket **t36** *builds* the host \
         adapters:\n\n\
         | binding | EC2 daemon (`host-daemon`) | Cloudflare Workers (`host-workers`, parked) |\n\
         |---------|---------------------------|---------------------------------------------|\n\
         | `ENDPOINT` | the cfs-http listener | Worker `fetch` |\n\
         | `JOB` | the cfs-cron interval daemon | Cron Trigger |\n\
         | `WEBHOOK` / event | the watchtower bus + `/hooks/...` ingest | Queues |\n\
         | watcher / `LAST_RUN` | the on-disk durable store | Durable Object |\n\
         | `/d1` · `/r2` · `/kv` | (native only on Workers) | native bindings |\n\n\
         The Workers host is honestly **parked** (the worker crate is offline in this build); the \
         EC2 daemon is the live target. See ADR-0005 and ADR-0007 for the offline/disk scoping.\n"
    );
    s
}

/// The verb rows for the capabilities table, in declaration order — supported AND unsupported,
/// so the catalog documents capabilities explicitly, never by omission (RFD §5).
fn capability_rows(c: &Capabilities) -> [(&'static str, bool); 9] {
    [
        ("SELECT", c.select),
        ("INSERT", c.insert),
        ("UPSERT", c.upsert),
        ("UPDATE", c.update),
        ("REMOVE", c.remove),
        ("LS", c.ls),
        ("CP", c.cp),
        ("MV", c.mv),
        ("RM", c.rm),
    ]
}

/// The driver id for a `CALL <id>.action(..)` from a mount (`/mail` → `mail`).
fn mount_id(mount: &str) -> &str {
    mount.strip_prefix('/').unwrap_or(mount)
}

/// A generated doc: its repo-relative path and its rendered content.
pub struct GeneratedDoc {
    /// Repo-relative path (e.g. `docs/language.md`).
    pub rel_path: &'static str,
    /// The fully rendered markdown.
    pub content: String,
}

/// Render every generated doc (used by both write and check modes).
#[must_use]
pub fn all_docs() -> Vec<GeneratedDoc> {
    vec![
        GeneratedDoc {
            rel_path: LANGUAGE_DOC,
            content: render_language(),
        },
        GeneratedDoc {
            rel_path: DRIVERS_DOC,
            content: render_drivers(),
        },
        GeneratedDoc {
            rel_path: SERVER_DOC,
            content: render_server(),
        },
    ]
}

/// Write every generated doc under `repo_root`. Returns the list of written paths.
///
/// # Errors
/// Propagates any filesystem error (the only I/O in this module — confined to the write tool).
pub fn gen_docs(repo_root: &Path) -> std::io::Result<Vec<PathBuf>> {
    let mut written = Vec::new();
    for doc in all_docs() {
        let path = repo_root.join(doc.rel_path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, doc.content.as_bytes())?;
        written.push(path);
    }
    Ok(written)
}

/// A doc-drift mismatch (`--check` mode): which file differs.
#[derive(Debug)]
pub struct DriftError {
    /// The repo-relative path that is out of date.
    pub rel_path: &'static str,
}

/// Check every generated doc against its committed file without writing (CI `--check` mode).
/// Returns the list of drifted files (empty == all in sync).
///
/// # Errors
/// Propagates a read error for a missing committed doc (a missing doc is itself drift).
pub fn check_docs(repo_root: &Path) -> std::io::Result<Vec<DriftError>> {
    let mut drift = Vec::new();
    for doc in all_docs() {
        let path = repo_root.join(doc.rel_path);
        let committed = std::fs::read_to_string(&path).unwrap_or_default();
        if committed != doc.content {
            drift.push(DriftError {
                rel_path: doc.rel_path,
            });
        }
    }
    Ok(drift)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Idempotency: rendering twice yields byte-identical output (gen-docs is a pure function of
    /// the binary's data, so re-running produces no diff — the t40 idempotency acceptance).
    #[test]
    fn rendering_is_idempotent() {
        assert_eq!(render_language(), render_language());
        assert_eq!(render_drivers(), render_drivers());
        assert_eq!(render_server(), render_server());
    }

    /// The language doc carries the full frozen keyword table and the grammar fence.
    #[test]
    fn language_doc_carries_frozen_keywords_and_grammar() {
        let doc = render_language();
        for kw in RESERVED_KEYWORDS {
            assert!(
                doc.contains(&format!("`{kw}`")),
                "keyword {kw} in language.md"
            );
        }
        assert!(doc.contains("```ebnf"), "grammar fence present");
        assert!(doc.contains("DESCRIBE → write a statement → PREVIEW → COMMIT"));
    }

    /// The drivers doc renders unsupported verbs explicitly (a `✗` row), never by omission.
    #[test]
    fn drivers_doc_shows_unsupported_verbs_explicitly() {
        let doc = render_drivers();
        assert!(doc.contains("# cfs driver catalog"));
        assert!(
            doc.contains('✗'),
            "unsupported verbs rendered as ✗, not omitted"
        );
        assert!(doc.contains('✓'), "supported verbs rendered as ✓");
        // At least one driver's irreversible proc surfaces (mail.send).
        assert!(doc.contains("`send`"));
    }

    /// The server doc carries every CREATE binding form + the t36 deployment mapping.
    #[test]
    fn server_doc_carries_bindings_and_mapping() {
        let doc = render_server();
        for kw in [
            "CREATE ENDPOINT",
            "CREATE TRIGGER",
            "CREATE JOB",
            "CREATE VIEW",
            "CREATE WEBHOOK",
            "CREATE POLICY",
        ] {
            assert!(doc.contains(kw), "{kw} documented in server.md");
        }
        assert!(doc.contains("Deployment mapping"));
        assert!(doc.contains("RuntimeHost"));
    }

    /// No live-credential shape appears in any generated doc (RFD §10): placeholders only.
    #[test]
    fn generated_docs_carry_no_live_credentials() {
        for doc in all_docs() {
            let body = doc.content.to_lowercase();
            assert!(
                !body.contains("bearer "),
                "{}: no bearer token",
                doc.rel_path
            );
            // No obvious secret assignment shapes.
            for needle in ["aws_secret", "password=", "token=", "api_key=", "ghp_"] {
                assert!(
                    !body.contains(needle),
                    "{}: no `{needle}` credential shape",
                    doc.rel_path
                );
            }
        }
    }

    /// **Docs-drift golden (t40 anti-drift acceptance).** The committed `docs/*.md` must equal
    /// what `gen-docs` renders right now — so adding a keyword / driver / codec without
    /// regenerating the docs fails `cargo test` (the same diff `xtask gen-docs --check` enforces
    /// in CI). This runs in an EXISTING test binary (cfs's lib tests), not a new one.
    #[test]
    fn committed_docs_match_generated_output() {
        // The repo root is two levels up from this crate (`crates/cfs`).
        let repo_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent())
            .expect("crates/cfs has a grandparent (the repo root)");
        let drift = check_docs(repo_root).expect("docs are readable");
        assert!(
            drift.is_empty(),
            "committed docs are stale: {:?}. Run `cargo run -p xtask -- gen-docs` and commit.",
            drift.iter().map(|d| d.rel_path).collect::<Vec<_>>()
        );
    }

    /// The generated banner cites the generator and forbids hand edits (the version surface is
    /// also exercised so it stays linked to docs generation).
    #[test]
    fn every_doc_is_banner_stamped() {
        assert!(!crate::version::VERSION.is_empty());
        for doc in all_docs() {
            assert!(
                doc.content
                    .starts_with("<!-- GENERATED by `cargo xtask gen-docs`"),
                "{} must carry the do-not-edit banner",
                doc.rel_path
            );
        }
    }
}
