//! The **`wrangler.toml` generator** (t36, RFD-0001 §8/§10): enumerate the Cloudflare deployment
//! bindings — Cron Triggers, Queues, the Durable Object class, and the d1/r2/kv native bindings —
//! from a derived [`BindingSet`], by **NAME ONLY**.
//!
//! The generated file is a TEMPLATE: it references binding names, queue names, the DO class, and
//! the resource names a deployer fills in `id`/`database_id` for. It **NEVER** embeds a token, a
//! secret, or a `database_id` value (RFD §10: wasm must never embed a token; the wrangler
//! references binding names only). Secrets are supplied out-of-band via `wrangler secret put`; the
//! template documents the required secret HANDLES as comments, never their values.
//!
//! The output is deterministic (sorted, stable formatting) so it golden-tests against a checked-in
//! fixture.

use crate::dto::{BindingSet, NativeStoreKind};

/// The Durable Object class name the watcher cursors / `LAST_RUN` high-water marks bind to (RFD
/// §8: stateful watcher/`LAST_RUN` → Durable Object). One class services every watcher's durable
/// state via [`crate::DurableStore`].
pub const DURABLE_OBJECT_CLASS: &str = "WatchtowerState";

/// The wasm module name the Worker `main` is built into (the `qfs.wasm` artifact, RFD §9).
pub const WORKER_MODULE: &str = "qfs";

/// Generate a `wrangler.toml` template from a derived [`BindingSet`]. The `worker_name` is the
/// deployment's Worker name (top-level `name =`). Deterministic + name-only.
#[must_use]
pub fn generate_wrangler_toml(worker_name: &str, set: &BindingSet) -> String {
    let mut out = String::new();
    out.push_str(
        "# Generated by `qfs` (t36 host-workers). Binding NAMES only — never a token or\n",
    );
    out.push_str(
        "# secret (RFD-0001 §10). Fill `id`/`database_id` and run `wrangler secret put`\n",
    );
    out.push_str("# for each signing-secret handle below before deploying.\n");
    out.push_str(&format!("name = \"{worker_name}\"\n"));
    out.push_str(&format!("main = \"{WORKER_MODULE}.wasm\"\n"));
    out.push_str("compatibility_date = \"2024-01-01\"\n");

    // ENDPOINT causes are served by the single `fetch` handler — they need no wrangler binding,
    // but we document them as a comment so the operator sees the route surface.
    if !set.endpoints.is_empty() {
        out.push('\n');
        out.push_str("# ENDPOINT causes (served by the Worker `fetch` handler):\n");
        for ep in &set.endpoints {
            let method = if ep.method.is_empty() {
                "ANY"
            } else {
                &ep.method
            };
            out.push_str(&format!(
                "#   {} {}  (handler `{}`)\n",
                method, ep.route, ep.name
            ));
        }
    }

    // JOB causes → Cron Triggers (the `crontab` expressions, sorted by job name for determinism).
    if !set.jobs.is_empty() {
        out.push_str("\n[triggers]\n");
        let mut crons: Vec<&str> = set.jobs.iter().map(|j| j.cron.as_str()).collect();
        crons.sort_unstable();
        crons.dedup();
        let list = crons
            .iter()
            .map(|c| format!("\"{c}\""))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("crons = [{list}]\n"));
    }

    // The Durable Object class (one class services every watcher's cursor / LAST_RUN).
    if !set.watchers.is_empty() {
        out.push_str("\n[durable_objects]\n");
        out.push_str(&format!(
            "bindings = [{{ name = \"{}\", class_name = \"{}\" }}]\n",
            DURABLE_OBJECT_CLASS, DURABLE_OBJECT_CLASS
        ));
        out.push_str("\n# Watcher causes (durable cursor / LAST_RUN via the DO above):\n");
        for w in &set.watchers {
            out.push_str(&format!(
                "#   trigger `{}` on `{}`  (cursor key `{}`)\n",
                w.name,
                w.on,
                w.cursor_key().as_str()
            ));
        }
    }

    // WEBHOOK/event causes → Queues (a producer per webhook). Sorted by queue name.
    if !set.webhooks.is_empty() {
        out.push_str("\n[[queues.producers]]\n");
        let mut webhooks: Vec<&crate::dto::WebhookBinding> = set.webhooks.iter().collect();
        webhooks.sort_by(|a, b| a.queue.cmp(&b.queue));
        for (i, wh) in webhooks.iter().enumerate() {
            if i > 0 {
                out.push_str("\n[[queues.producers]]\n");
            }
            out.push_str(&format!("queue = \"{}\"\n", wh.queue));
            out.push_str(&format!("binding = \"{}\"\n", queue_binding_name(&wh.name)));
            if !wh.secret_handle.is_empty() {
                out.push_str(&format!(
                    "# signing-secret handle (run `wrangler secret put {}`): {}\n",
                    secret_env_name(&wh.name),
                    wh.secret_handle
                ));
            }
        }
        // One consumer per queue (the Worker `queue` handler drains it).
        for wh in &webhooks {
            out.push_str("\n[[queues.consumers]]\n");
            out.push_str(&format!("queue = \"{}\"\n", wh.queue));
        }
    }

    // Native-store bindings → d1/r2/kv (already sorted + de-duplicated in the BindingSet).
    for ns in &set.native_stores {
        match ns.kind {
            NativeStoreKind::D1 => {
                out.push_str("\n[[d1_databases]]\n");
                out.push_str(&format!("binding = \"{}\"\n", ns.binding_name()));
                out.push_str(&format!("database_name = \"{}\"\n", ns.resource));
                out.push_str("database_id = \"\"  # fill in: wrangler d1 list\n");
            }
            NativeStoreKind::R2 => {
                out.push_str("\n[[r2_buckets]]\n");
                out.push_str(&format!("binding = \"{}\"\n", ns.binding_name()));
                out.push_str(&format!("bucket_name = \"{}\"\n", ns.resource));
            }
            NativeStoreKind::Kv => {
                out.push_str("\n[[kv_namespaces]]\n");
                out.push_str(&format!("binding = \"{}\"\n", ns.binding_name()));
                out.push_str("id = \"\"  # fill in: wrangler kv:namespace list\n");
            }
        }
    }

    out
}

/// The Queue producer binding name the Worker references as `env.<name>` to publish a webhook
/// event. Derived name-only as `<NAME>_QUEUE`.
fn queue_binding_name(webhook: &str) -> String {
    format!("{}_QUEUE", sanitize(webhook))
}

/// The secret env name a signed webhook's signing-secret is bound to (`wrangler secret put`).
fn secret_env_name(webhook: &str) -> String {
    format!("{}_SECRET", sanitize(webhook))
}

/// Uppercase alnum + `_` identifier sanitizer (matches the native-store binding rule).
fn sanitize(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dto::{
        EndpointBinding, JobBinding, Mount, NativeStoreBinding, WatcherBinding, WebhookBinding,
    };

    fn sample() -> BindingSet {
        BindingSet {
            endpoints: vec![EndpointBinding {
                name: "recent".to_string(),
                method: "GET".to_string(),
                route: "/recent".to_string(),
                policy: None,
            }],
            jobs: vec![JobBinding {
                name: "nightly".to_string(),
                every: "1h".to_string(),
                cron: "0 * * * *".to_string(),
                policy: Some("leastpriv".to_string()),
            }],
            webhooks: vec![WebhookBinding {
                name: "inbound".to_string(),
                route: "/hooks/x".to_string(),
                secret_handle: "wh-secret".to_string(),
                queue: "inbound-events".to_string(),
            }],
            watchers: vec![WatcherBinding {
                name: "notify".to_string(),
                on: "inbox".to_string(),
                policy: Some("leastpriv".to_string()),
            }],
            native_stores: vec![NativeStoreBinding {
                kind: NativeStoreKind::D1,
                resource: "analytics".to_string(),
                mount: Mount::new("/cf/d1/analytics"),
            }],
        }
    }

    #[test]
    fn generated_toml_carries_no_secret_value() {
        let toml = generate_wrangler_toml("qfs-app", &sample());
        // The HANDLE may appear (it is a non-secret reference); a token VALUE never would.
        assert!(toml.contains("crons = [\"0 * * * *\"]"));
        assert!(toml.contains("class_name = \"WatchtowerState\""));
        assert!(toml.contains("queue = \"inbound-events\""));
        assert!(toml.contains("binding = \"D1_ANALYTICS\""));
        assert!(toml.contains("database_name = \"analytics\""));
        // No database_id VALUE is ever emitted (left blank for the deployer).
        assert!(toml.contains("database_id = \"\""));
    }

    #[test]
    fn generation_is_deterministic() {
        let a = generate_wrangler_toml("qfs-app", &sample());
        let b = generate_wrangler_toml("qfs-app", &sample());
        assert_eq!(a, b);
    }
}
