import { defineConfig } from 'vitepress'
import { qfsGrammar } from './qfs.tmLanguage.js'

// VitePress config for the qfs documentation site.
// srcDir is this `docs/` tree (the site is launched with `vitepress dev docs`), so the links
// below are relative to docs/. The reference pages (language/drivers/server) are GENERATED by
// `cargo run -p xtask -- gen-docs` from the binary's own registries — do not hand-edit them.
export default defineConfig({
  title: 'qfs',
  description: 'One query language for every service you use — mail, databases, GitHub, Slack, files, git, the cloud.',
  ignoreDeadLinks: true,
  // Allow the dev server to be reached through the cloudflared tunnel hostname.
  vite: {
    server: {
      allowedHosts: ['docs-qfs.qmu.dev'],
    },
  },
  markdown: {
    // Register the custom qfs highlighter so ```qfs blocks are syntax-highlighted.
    languages: [qfsGrammar as any],
  },
  themeConfig: {
    // Show H2 + H3 in the right-hand "On this page" outline, so the query cookbook's
    // `## Part N` headers appear with their `### N.M` subsections nested under them
    // (the default level-2-only outline hid the Part groupings).
    outline: { level: [2, 3], label: 'On this page' },
    nav: [
      { text: 'Get started', link: '/guide/getting-started' },
      { text: 'Cookbook', link: '/cookbook/' },
      { text: 'Query cookbook', link: '/query-cookbook' },
      {
        text: 'Reference',
        items: [
          { text: 'Language', link: '/language' },
          { text: 'Driver catalog', link: '/drivers' },
          { text: 'Server', link: '/server' },
          { text: 'CLI', link: '/guide/cli' },
        ],
      },
      { text: 'Roadmap', link: '/roadmap' },
    ],
    // One shared sidebar across every page (an array, not a path-keyed object) so navigating into
    // the Cookbook doesn't hide the rest of the docs. Sections are collapsible.
    sidebar: [
      {
        text: 'Get started',
        items: [
          { text: 'Installation', link: '/guide/installation' },
          { text: 'Get started', link: '/guide/getting-started' },
          { text: 'The QFS passphrase', link: '/guide/passphrase' },
          { text: 'The operator identity', link: '/guide/operator' },
          { text: 'Connect a service', link: '/guide/connect' },
        ],
      },
      {
        text: 'Cookbook',
        collapsed: false,
        items: [
          { text: 'Overview', link: '/cookbook/' },
          { text: 'Gmail', link: '/cookbook/gmail' },
          { text: 'Google Drive', link: '/cookbook/gdrive' },
          { text: 'Databases', link: '/cookbook/databases' },
          { text: 'git', link: '/cookbook/git' },
          { text: 'GitHub', link: '/cookbook/github' },
          { text: 'Slack', link: '/cookbook/slack' },
          { text: 'Files & object storage', link: '/cookbook/files' },
          { text: 'Cross-service', link: '/cookbook/cross-service' },
          { text: 'Automation (server)', link: '/cookbook/automation' },
          { text: 'Query cookbook (catalogue)', link: '/query-cookbook' },
        ],
      },
      {
        text: 'Using qfs',
        items: [
          { text: 'How qfs works', link: '/guide/concepts' },
          { text: 'CLI reference', link: '/guide/cli' },
          { text: 'Interactive shell', link: '/guide/shell' },
          { text: 'Connections & credentials', link: '/guide/connections' },
          { text: 'Where qfs is going (roadmap)', link: '/roadmap' },
        ],
      },
      {
        text: 'Reference (generated)',
        items: [
          { text: 'Language', link: '/language' },
          { text: 'Driver catalog', link: '/drivers' },
          { text: 'Server guide', link: '/server' },
        ],
      },
      {
        text: 'Architecture Decisions',
        collapsed: true,
        items: [
          { text: '0001 — Parser library', link: '/adr/0001-parser-library' },
          { text: '0002 — Local combine engine', link: '/adr/0002-local-combine-engine' },
          { text: '0003 — Git object access', link: '/adr/0003-git-object-access' },
          { text: '0004 — HTTP serving', link: '/adr/0004-http-serving' },
          { text: '0005 — Deployment hosts', link: '/adr/0005-deployment-hosts' },
          { text: '0006 — Test harness', link: '/adr/0006-test-harness' },
          { text: '0007 — Docs and distribution', link: '/adr/0007-docs-and-distribution' },
        ],
      },
      {
        text: 'Security',
        collapsed: true,
        items: [{ text: 'Threat model', link: '/security/threat-model' }],
      },
    ],
    socialLinks: [{ icon: 'github', link: 'https://github.com/qmu/qfs' }],
    search: { provider: 'local' },
  },
})
