//! THROWAWAY t02 comparison test — NOT production. See docs/adr/0001-parser-library.md.
//!
//! Two checks form the ADR evidence:
//!   1. Cross-parser AST equality on every valid corpus input (apples-to-apples).
//!   2. A committed golden error corpus: the rendered error from each parser for
//!      every broken input, locked against `tests/golden/errors.txt`.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use parser_spike::{chumsky_spike, winnow_spike, CORPUS};

/// (1) On valid inputs both parsers must produce the IDENTICAL shared AST.
#[test]
fn winnow_and_chumsky_agree_on_valid_inputs() {
    for case in CORPUS.iter().filter(|c| c.valid) {
        let w = winnow_spike::parse(case.input);
        let c = chumsky_spike::parse(case.input);
        assert!(w.is_ok(), "[{}] winnow failed: {w:?}", case.label);
        assert!(c.is_ok(), "[{}] chumsky failed: {c:?}", case.label);
        assert_eq!(
            w.unwrap(),
            c.unwrap(),
            "[{}] winnow and chumsky produced different ASTs",
            case.label
        );
    }
}

/// (2) Both parsers reject every broken input (sanity: no false accept).
#[test]
fn both_reject_broken_inputs() {
    for case in CORPUS.iter().filter(|c| !c.valid) {
        assert!(
            winnow_spike::parse(case.input).is_err(),
            "[{}] winnow unexpectedly accepted",
            case.label
        );
        assert!(
            chumsky_spike::parse(case.input).is_err(),
            "[{}] chumsky unexpectedly accepted",
            case.label
        );
    }
}

/// Render the full golden corpus (both parsers, all broken inputs).
fn render_golden() -> String {
    let mut out = String::new();
    out.push_str("# t02 golden error corpus (winnow vs chumsky)\n");
    out.push_str("# Generated by spikes/parser-spike tests. NOT production.\n");
    out.push_str("# See docs/adr/0001-parser-library.md.\n");
    for case in CORPUS.iter().filter(|c| !c.valid) {
        out.push_str(&format!(
            "\n## case: {} | input: {:?}\n",
            case.label, case.input
        ));
        let w = winnow_spike::parse(case.input)
            .err()
            .map_or_else(|| "UNEXPECTEDLY OK".to_string(), |e| e.render());
        out.push_str(&format!("winnow:  {w}\n"));
        let c = chumsky_spike::parse(case.input)
            .err()
            .map_or_else(|| "UNEXPECTEDLY OK".to_string(), |e| e.render());
        out.push_str(&format!("chumsky: {c}\n"));
        let multi = chumsky_spike::parse_all_errors(case.input);
        out.push_str(&format!("chumsky-recovery-count: {}\n", multi.len()));
    }
    out
}

/// (3) Golden lock. Set `UPDATE_GOLDEN=1` to regenerate the committed file.
#[test]
fn golden_error_corpus_is_stable() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden/errors.txt");
    let actual = render_golden();
    if std::env::var("UPDATE_GOLDEN").is_ok() {
        std::fs::create_dir_all(concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden")).unwrap();
        std::fs::write(path, &actual).unwrap();
        return;
    }
    let expected = std::fs::read_to_string(path)
        .expect("golden file missing; run with UPDATE_GOLDEN=1 to create it");
    assert_eq!(
        actual, expected,
        "golden error corpus drifted; rerun with UPDATE_GOLDEN=1 if intentional"
    );
}
