//! `qfs::docs` — the **anti-drift documentation generator** (ticket t40).
//!
//! `cargo xtask gen-docs` calls [`gen_docs`] (write mode) or [`check_docs`] (CI `--check`
//! mode). Both render the three generated reference docs **from the binary's own data** so the
//! published reference can never drift from the code:
//!
//! - `docs/language.md` ← [`qfs_lang::RESERVED_KEYWORDS`] + [`qfs_lang::grammar_ebnf`] (the
//!   frozen §3 vocabulary + the grammar; the reserved-word table is the one frozen slice).
//! - `docs/drivers.md` ← [`crate::catalog::driver_catalog`] (archetypes / capabilities /
//!   procedures / codecs, folded from the t39 describe surface — never hand-authored).
//! - `docs/server.md` ← the frozen server-DDL keyword set (create endpoint|trigger|job|view|
//!   webhook|policy) + the t36 deployment mapping prose.
//!
//! The render functions are **pure** `-> String`: no creds, no live tokens, only schema +
//! capabilities (RFD §10). The golden/idempotency test ([`tests`]) and the `--check` mode
//! compare the rendered string to the committed file; a keyword/driver/codec change that is not
//! reflected in `docs/` fails the check (anti-drift enforcement, RFD §3).

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use qfs_core::{grammar_ebnf, Capabilities, RESERVED_KEYWORDS};

use crate::catalog::{driver_catalog, Catalog, DriverDoc};

/// The three generated reference files, relative to the repo root.
pub const LANGUAGE_DOC: &str = "docs/language.md";
/// The generated driver-catalog doc.
pub const DRIVERS_DOC: &str = "docs/drivers.md";
/// The generated server-guide doc.
pub const SERVER_DOC: &str = "docs/server.md";

/// A do-not-edit banner stamped at the top of every generated doc, pointing the editor at the
/// generator (so a human never hand-edits a generated file and reintroduces drift).
fn generated_banner(source: &str) -> String {
    format!(
        "<!-- GENERATED by `cargo xtask gen-docs` from {source}. DO NOT EDIT BY HAND. -->\n\
         <!-- Re-run `cargo xtask gen-docs` after changing the source; CI fails on drift. -->\n\n"
    )
}

/// Render `docs/language.md` from the frozen reserved-word set + the EBNF grammar.
#[must_use]
pub fn render_language() -> String {
    let mut s = generated_banner("qfs-lang (RESERVED_KEYWORDS + grammar_ebnf)");
    let _ = writeln!(s, "# qfs language reference\n");
    let _ = writeln!(
        s,
        "qfs is **one small pipe-SQL language** that works on every service. You write a query as a \
         source followed by stages joined by `|>` (a pipe), and the same grammar reads mail, \
         queries a database, joins across services, transforms formats, and writes changes.\n\n\
         The grammar is **fixed and small** — adding a new service never adds new keywords. A new \
         service is just a new path; a new action is a `call`; a new format is a `decode`/`encode`. \
         This page is generated from the binary itself, so it always matches the version you have \
         installed.\n"
    );

    let _ = writeln!(s, "## Reserved keywords\n");
    let _ = writeln!(
        s,
        "These {} words make up the whole language — written in **lowercase** (recognized \
         case-insensitively, so an older uppercase query still works). Because the set is fixed, \
         anything you learn here keeps working as new services are added.\n",
        RESERVED_KEYWORDS.len()
    );
    let _ = writeln!(s, "| # | keyword |");
    let _ = writeln!(s, "|---|---------|");
    for (i, kw) in RESERVED_KEYWORDS.iter().enumerate() {
        let _ = writeln!(s, "| {} | `{}` |", i + 1, kw);
    }
    s.push('\n');

    let _ = writeln!(s, "## Grammar (EBNF)\n");
    let _ = writeln!(
        s,
        "The pipe-SQL grammar. Every quoted lowercase terminal is a frozen reserved keyword above; \
         the quoted UPPERCASE terminals are the word operators (`AND`/`OR`/`NOT`/`LIKE`/`IN`/`ANY`/\
         `BETWEEN`).\n"
    );
    let _ = writeln!(s, "```text\n{}```\n", grammar_ebnf());

    let _ = writeln!(s, "## Nothing happens until you commit\n");
    let _ = writeln!(
        s,
        "Writing a statement never acts on its own. A statement *plans* an effect; `preview` (the \
         default) shows you that plan without touching anything, and `commit` applies it. Even a \
         convenience alias like `send(...)` doesn't send — it just adds a `call mail.send` step to \
         the plan you preview first. This is what makes the whole loop safe: \
         **describe → write → preview → commit**.\n"
    );

    let _ = writeln!(s, "## Extending qfs\n");
    let _ = writeln!(
        s,
        "The language never grows new keywords. Everything new a service needs is one of three \
         things:\n\n\
         - **a path** — a new service mounted at a new prefix (e.g. `/mail`, `/s3`); see the \
           [driver catalog](drivers.md).\n\
         - **an action** — a `call service.action(..)` procedure (and optional alias).\n\
         - **a format** — a `decode`/`encode` codec; see the [driver catalog](drivers.md).\n\n\
         Because the language stays fixed, you learn it once and every service speaks it.\n"
    );

    s
}

/// Render one driver's catalog row, capabilities shown explicitly (supported AND unsupported).
fn render_driver(s: &mut String, d: &DriverDoc) {
    let _ = writeln!(s, "### `{}` — {:?}\n", d.mount, d.archetype);
    let _ = writeln!(s, "- example node: `{}`", d.example_path);
    let _ = writeln!(s, "- native verbs: {}\n", d.native_verbs);

    let _ = writeln!(
        s,
        "Universal verbs (✓ supported / ✗ rejected at parse time):\n"
    );
    let _ = writeln!(s, "| verb | supported |");
    let _ = writeln!(s, "|------|-----------|");
    for (verb, on) in capability_rows(&d.capabilities) {
        let _ = writeln!(s, "| `{verb}` | {} |", if on { "✓" } else { "✗" });
    }
    s.push('\n');

    if d.procedures.is_empty() {
        let _ = writeln!(s, "Procedures: _none_\n");
    } else {
        let _ = writeln!(
            s,
            "Procedures (`call {}.action(..)`):\n",
            mount_id(&d.mount)
        );
        let _ = writeln!(s, "| procedure | params | irreversible |");
        let _ = writeln!(s, "|-----------|--------|--------------|");
        for p in &d.procedures {
            let params = p
                .params
                .iter()
                .map(|pm| format!("{}: {:?}", pm.name, pm.ty))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(
                s,
                "| `{}` | {} | {} |",
                p.name,
                if params.is_empty() {
                    "—".into()
                } else {
                    params
                },
                if p.irreversible { "yes" } else { "no" }
            );
        }
        s.push('\n');
    }

    if d.aliases.is_empty() {
        let _ = writeln!(s, "Prelude aliases: _none_\n");
    } else {
        let aliases = d
            .aliases
            .iter()
            .map(|(n, t)| format!("`{n}` → `{t}`"))
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(s, "Prelude aliases: {aliases}\n");
    }

    let pd = &d.pushdown;
    let _ = writeln!(
        s,
        "Pushdown: where={} project={} limit={} order={} join={} aggregate={} distinct={} group_by={}\n",
        pd.where_, pd.project, pd.limit, pd.order, pd.join, pd.aggregate, pd.distinct, pd.group_by
    );
}

/// Render `docs/drivers.md` from the live driver catalog.
#[must_use]
pub fn render_drivers() -> String {
    let cat: Catalog = driver_catalog();
    let mut s = generated_banner("the live driver catalog (qfs::catalog::driver_catalog)");
    let _ = writeln!(s, "# qfs driver catalog\n");
    let _ = writeln!(
        s,
        "Every service is mounted at a path prefix (e.g. `/mail`, `/s3`). Each one has a shape — \
         one of four archetypes (Blob, Relational, Append, ObjectGraph) — that decides which verbs \
         it supports. A path only offers the verbs that make sense for it; using an unsupported \
         verb is **rejected immediately with a clear error**, never half-applied. The catalog \
         below is generated from your installed binary, so it always matches what you have.\n\n\
         The verbs are always `select` / `insert` / `upsert` / `update` / `remove` (plus `call`). \
         Where a `native verbs` line mentions `ls`/`cp`/`mv`/`rm`, those are just familiar \
         filesystem **aliases** for the same verbs in the interactive shell (`ls` is a `select`, \
         `cp` an `upsert`, `rm` a `remove`) — not a second set of operations.\n"
    );

    let _ = writeln!(s, "## Drivers\n");
    for d in &cat.drivers {
        render_driver(&mut s, d);
    }

    let _ = writeln!(s, "## Codecs (decode / encode formats)\n");
    let _ = writeln!(
        s,
        "Codecs bridge blob ↔ relational independent of driver identity. Builtin formats:\n"
    );
    for c in &cat.codecs {
        let _ = writeln!(s, "- `{c}`");
    }
    s.push('\n');
    s
}

/// Render `docs/server.md` from the server binding forms + deployment targets.
#[must_use]
pub fn render_server() -> String {
    let mut s = generated_banner("the server binding forms + deployment targets");
    let _ = writeln!(s, "# qfs server guide\n");
    let _ = writeln!(
        s,
        "`qfs serve <config.qfs>` runs the server from a config file. A config is just a list of \
         `create …` bindings — each one takes a query you already know and runs it on an event, a \
         schedule, or an HTTP request. Bindings use the same language as everything else (see the \
         [language reference](language.md)), so you can preview exactly what a binding would do \
         before installing it.\n"
    );

    let _ = writeln!(s, "## Bindings (`create …`)\n");
    let _ = writeln!(s, "| binding | shape | what causes the plan to run |");
    let _ = writeln!(s, "|---------|-------|-----------------------------|");
    let _ = writeln!(
        s,
        "| `create endpoint` | `endpoint <name> do <stmt>` | an HTTP `fetch` to the endpoint route |"
    );
    let _ = writeln!(
        s,
        "| `create trigger` | `trigger <name> on <event> do <stmt>` | an event/watcher firing |"
    );
    let _ = writeln!(
        s,
        "| `create job` | `job <name> every <interval> do <stmt>` | a saved plan an EXTERNAL scheduler runs (`qfs job run` from OS cron; Cloudflare Cron Triggers) |"
    );
    let _ = writeln!(
        s,
        "| `create view` | `[materialized] view <name> as <pipeline>` | a query against the view |"
    );
    let _ = writeln!(
        s,
        "| `create webhook` | `webhook <name> do <stmt>` | a signed inbound `/hooks/...` POST |"
    );
    let _ = writeln!(
        s,
        "| `create policy` | `policy <name> <predicate>` | (gate) blocks plans that violate it |"
    );
    s.push('\n');

    let _ = writeln!(s, "## Policy & least privilege\n");
    let _ = writeln!(
        s,
        "`create policy` gates writes by verb / path / irreversibility — an irreversible effect \
         (`remove`, `call mail.send`) can be blocked or required to be explicitly acknowledged. \
         **Credentials are never inline in a config**: a binding references a stored connection by \
         handle (`qfs connection add <driver> <name>`), and no token is ever written to a config, a \
         log, or a generated doc. Examples below use placeholder handles only.\n"
    );
    let _ = writeln!(
        s,
        "```qfs\n\
         create endpoint recent on 'GET /recent' as /mail/inbox |> limit 5\n\
         create trigger notify on /mail/inbox do insert into /slack/acme/general/messages values (NEW.subject)\n\
         create job nightly every '1h' do remove /tmp/scratch where age > 7\n\
         create policy api ALLOW select DENY insert, update, remove, call\n\
         ```\n"
    );

    let _ = writeln!(s, "## Deployment targets\n");
    let _ = writeln!(
        s,
        "The same bindings deploy onto two production hosts behind the `RuntimeHost` seam \
         (ADR-0005). `qfs` *documents* the mapping here; ticket **t36** *builds* the host \
         adapters:\n\n\
         | binding | EC2 daemon (`host-daemon`) | Cloudflare Workers (`host-workers`, parked) |\n\
         |---------|---------------------------|---------------------------------------------|\n\
         | `endpoint` | the qfs-http listener | Worker `fetch` |\n\
         | `job` | OS `cron` runs `qfs job run` (no internal scheduler) | Cron Trigger |\n\
         | `webhook` / event | the watchtower bus + `/hooks/...` ingest | Queues |\n\
         | watcher / `LAST_RUN` | the on-disk durable store | Durable Object |\n\
         | `/d1` · `/r2` · `/kv` | (native only on Workers) | native bindings |\n\n\
         The Workers host is honestly **parked** (the worker crate is offline in this build); the \
         EC2 daemon is the live target. See ADR-0005 and ADR-0007 for the offline/disk scoping.\n"
    );
    s
}

/// The verb rows for the capabilities table, in declaration order — supported AND unsupported,
/// so the catalog documents capabilities explicitly, never by omission (RFD §5).
fn capability_rows(c: &Capabilities) -> [(&'static str, bool); 9] {
    [
        ("select", c.select),
        ("insert", c.insert),
        ("upsert", c.upsert),
        ("update", c.update),
        ("remove", c.remove),
        ("ls", c.ls),
        ("cp", c.cp),
        ("mv", c.mv),
        ("rm", c.rm),
    ]
}

/// The driver id for a `CALL <id>.action(..)` from a mount (`/mail` → `mail`).
fn mount_id(mount: &str) -> &str {
    mount.strip_prefix('/').unwrap_or(mount)
}

/// A generated doc: its repo-relative path and its rendered content.
pub struct GeneratedDoc {
    /// Repo-relative path (e.g. `docs/language.md`).
    pub rel_path: &'static str,
    /// The fully rendered markdown.
    pub content: String,
}

/// Render every generated doc (used by both write and check modes).
#[must_use]
pub fn all_docs() -> Vec<GeneratedDoc> {
    vec![
        GeneratedDoc {
            rel_path: LANGUAGE_DOC,
            content: render_language(),
        },
        GeneratedDoc {
            rel_path: DRIVERS_DOC,
            content: render_drivers(),
        },
        GeneratedDoc {
            rel_path: SERVER_DOC,
            content: render_server(),
        },
    ]
}

/// Write every generated doc under `repo_root`. Returns the list of written paths.
///
/// # Errors
/// Propagates any filesystem error (the only I/O in this module — confined to the write tool).
pub fn gen_docs(repo_root: &Path) -> std::io::Result<Vec<PathBuf>> {
    let mut written = Vec::new();
    for doc in all_docs() {
        let path = repo_root.join(doc.rel_path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, doc.content.as_bytes())?;
        written.push(path);
    }
    Ok(written)
}

/// A doc-drift mismatch (`--check` mode): which file differs.
#[derive(Debug)]
pub struct DriftError {
    /// The repo-relative path that is out of date.
    pub rel_path: &'static str,
}

/// Check every generated doc against its committed file without writing (CI `--check` mode).
/// Returns the list of drifted files (empty == all in sync).
///
/// # Errors
/// Propagates a read error for a missing committed doc (a missing doc is itself drift).
pub fn check_docs(repo_root: &Path) -> std::io::Result<Vec<DriftError>> {
    let mut drift = Vec::new();
    for doc in all_docs() {
        let path = repo_root.join(doc.rel_path);
        let committed = std::fs::read_to_string(&path).unwrap_or_default();
        if committed != doc.content {
            drift.push(DriftError {
                rel_path: doc.rel_path,
            });
        }
    }
    Ok(drift)
}

/// Resolve the git repo root by walking up from `start` until a directory holding a `.git` entry
/// is found. The top-level `docs/` tree (and the `DOC` paths above) live at that root, which sits
/// above the `packages/qfs/` Cargo workspace in the monorepo layout. Falls back to `start` when no
/// `.git` is found (e.g. a source tarball), preserving whatever layout is present.
#[must_use]
pub fn find_repo_root(start: &Path) -> PathBuf {
    let mut dir = Some(start);
    while let Some(d) = dir {
        if d.join(".git").exists() {
            return d.to_path_buf();
        }
        dir = d.parent();
    }
    start.to_path_buf()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Idempotency: rendering twice yields byte-identical output (gen-docs is a pure function of
    /// the binary's data, so re-running produces no diff — the t40 idempotency acceptance).
    #[test]
    fn rendering_is_idempotent() {
        assert_eq!(render_language(), render_language());
        assert_eq!(render_drivers(), render_drivers());
        assert_eq!(render_server(), render_server());
    }

    /// The language doc carries the full frozen keyword table and the grammar fence.
    #[test]
    fn language_doc_carries_frozen_keywords_and_grammar() {
        let doc = render_language();
        for kw in RESERVED_KEYWORDS {
            assert!(
                doc.contains(&format!("`{kw}`")),
                "keyword {kw} in language.md"
            );
        }
        assert!(
            doc.contains("(* qfs pipe-SQL grammar"),
            "EBNF grammar block present"
        );
        assert!(doc.contains("describe → write → preview → commit"));
    }

    /// The drivers doc renders unsupported verbs explicitly (a `✗` row), never by omission.
    #[test]
    fn drivers_doc_shows_unsupported_verbs_explicitly() {
        let doc = render_drivers();
        assert!(doc.contains("# qfs driver catalog"));
        assert!(
            doc.contains('✗'),
            "unsupported verbs rendered as ✗, not omitted"
        );
        assert!(doc.contains('✓'), "supported verbs rendered as ✓");
        // At least one driver's irreversible proc surfaces (mail.send).
        assert!(doc.contains("`send`"));
    }

    /// The server doc carries every CREATE binding form + the t36 deployment mapping.
    #[test]
    fn server_doc_carries_bindings_and_mapping() {
        let doc = render_server();
        for kw in [
            "create endpoint",
            "create trigger",
            "create job",
            "create view",
            "create webhook",
            "create policy",
        ] {
            assert!(doc.contains(kw), "{kw} documented in server.md");
        }
        assert!(doc.contains("Deployment targets"));
        assert!(doc.contains("RuntimeHost"));
    }

    /// No live-credential shape appears in any generated doc (RFD §10): placeholders only.
    #[test]
    fn generated_docs_carry_no_live_credentials() {
        for doc in all_docs() {
            let body = doc.content.to_lowercase();
            assert!(
                !body.contains("bearer "),
                "{}: no bearer token",
                doc.rel_path
            );
            // No obvious secret assignment shapes.
            for needle in ["aws_secret", "password=", "token=", "api_key=", "ghp_"] {
                assert!(
                    !body.contains(needle),
                    "{}: no `{needle}` credential shape",
                    doc.rel_path
                );
            }
        }
    }

    /// **Docs-drift golden (t40 anti-drift acceptance).** The committed `docs/*.md` must equal
    /// what `gen-docs` renders right now — so adding a keyword / driver / codec without
    /// regenerating the docs fails `cargo test` (the same diff `xtask gen-docs --check` enforces
    /// in CI). This runs in an EXISTING test binary (qfs's lib tests), not a new one.
    #[test]
    fn committed_docs_match_generated_output() {
        // The top-level `docs/` tree lives at the git repo root (above the packages/qfs
        // workspace), located by walking up to the `.git` dir.
        let repo_root = find_repo_root(std::path::Path::new(env!("CARGO_MANIFEST_DIR")));
        let drift = check_docs(&repo_root).expect("docs are readable");
        assert!(
            drift.is_empty(),
            "committed docs are stale: {:?}. Run `cargo run -p xtask -- gen-docs` and commit.",
            drift.iter().map(|d| d.rel_path).collect::<Vec<_>>()
        );
    }

    /// The generated banner cites the generator and forbids hand edits (the version surface is
    /// also exercised so it stays linked to docs generation).
    #[test]
    fn every_doc_is_banner_stamped() {
        assert!(!crate::version::VERSION.is_empty());
        for doc in all_docs() {
            assert!(
                doc.content
                    .starts_with("<!-- GENERATED by `cargo xtask gen-docs`"),
                "{} must carry the do-not-edit banner",
                doc.rel_path
            );
        }
    }
}
